### model
model_name_or_path: /root/soulv_assets/runs/merged/qwen3_32b_stage1_merged_base
adapter_name_or_path: /root/soulv_assets/runs/checkpoints/qwen3_32b_stage2_amap_tool_use
template: qwen
finetuning_type: lora
trust_remote_code: true

### export
export_dir: /root/soulv_assets/runs/merged/qwen3_32b_stage2_amap_tool_use_merged
export_size: 10
export_device: cpu
